Javascript2 week1/andrii
HackYourFuture-CPH/class26-homework pull request #137
Opened 2023-09-28 12:14 UTC by ayaroshenkocom

Here is my homework Javascript2 Week1

2023-09-30 16:26 UTC, szoboszlaianna requested changes

2023-09-30 16:26 UTC, szoboszlaianna commented on 3_javascript/javascript2/week1/script.js
> +function countDanishLetters(str) {
What about lowercase?

2023-09-30 16:26 UTC, szoboszlaianna commented on 3_javascript/javascript2/week1/script.js
> +            spiritAnimalResult.textContent = `Name: ${name}: ${name} - ${spiritAnimal}`;
This could be also be part of generateSpiritAnimal because it is the same for all three.

2023-10-14 20:24 UTC, ayaroshenkocom commented
Thank for your review and advice. I have fixed issues.

2023-10-14 20:24 UTC, closed without merging