Javascript2 week1/sevda
HackYourFuture-CPH/class26-homework pull request #142
Opened 2023-09-28 21:16 UTC by Sevda-NZ

Please review. Thanks in advance :)

2023-09-30 16:19 UTC, szoboszlaianna requested changes

2023-09-30 16:19 UTC, szoboszlaianna commented on 3_javascript/javascript2/week1/script.js
> +  let obj = {};
the function could be made more efficient for example by using an object to keep track of the numbers:   ` const danishVowels = { "æ": 0, "ø": 0, "å": 0 }`.  Also would be nice to check for capital letters as well.

2023-09-30 16:19 UTC, szoboszlaianna commented on 3_javascript/javascript2/week1/script.js
> +    document.querySelector("body").append(paragraph);
would be nice to create the previous one when generating a new.

2023-09-30 16:19 UTC, szoboszlaianna commented on 3_javascript/javascript2/week1/script.js
> +// Find and count the Danish letters
Where is the 3rd task?

2023-10-04 11:32 UTC, Sevda-NZ commented
Reviews are implemented :)

2023-10-04 11:32 UTC, closed without merging