Javascript2 week3/sevda
HackYourFuture-CPH/class26-homework pull request #164
Opened 2023-10-13 22:34 UTC by Sevda-NZ

Please review :)

2023-10-18 18:55 UTC, szoboszlaianna requested changes

2023-10-18 18:55 UTC, szoboszlaianna commented on 3_javascript/javascript2/week3/Exercise1-2/script.js
> +}
Why did you multiply by 2500? The `setTimeout` function expects the delay in milliseconds. If your function takes seconds, you should multiply it by 1000 to correctly convert it.

2023-10-18 18:55 UTC, szoboszlaianna commented on 3_javascript/javascript2/week3/game_1/script.js
> +let gameDuration = 0;
Nice work

2023-10-20 10:34 UTC, Sevda-NZ commented
implemented the reviews :)

2023-10-20 10:34 UTC, closed without merging