Databases week1 shahnawaz
HackYourFuture-CPH/class26-homework pull request #217
Opened 2023-11-09 11:29 UTC by shazkhan2

2023-11-14 09:43 UTC, adionditsak requested changes

2023-11-14 09:43 UTC, adionditsak commented on 5_databases/week1/command.sql
> +-- 3. Find all the tasks that are marked as done
Awesome interpretation. I would probably just think more simple and check the status table first and check status_id=3 directly, but this works as well

2023-11-14 09:43 UTC, adionditsak commented on 5_databases/week1/command.sql
> +SELECT status.name, user.id, task.description
same as above just with != (NOT equal operator)

2023-11-14 09:43 UTC, adionditsak commented on 5_databases/week1/command.sql
> +SELECT status.name, created
There is no reason to join here. We just want the task:
```

SELECT * 
FROM task 
ORDER BY created DESC;

```

2023-11-14 09:43 UTC, adionditsak commented on 5_databases/week1/command.sql
> +SELECT status.name, created
Same as above, keep it simple

2023-11-14 09:43 UTC, adionditsak commented on 5_databases/week1/command.sql
> +SELECT task.title, task.description
The task asks us to retrieve title and due_date, not description. Well done tho!

2023-11-14 09:43 UTC, adionditsak commented on 5_databases/week1/command.sql
> +SELECT task.title, status.name AS status_text
Well done!

2023-11-14 09:43 UTC, adionditsak commented on 5_databases/week1/command.sql
> +SELECT status.name, COUNT(*) AS status_count
Well done!

2023-11-22 18:16 UTC, shazkhan2 commented on 5_databases/week1/command.sql
> +SELECT status.name, created
updated as recommended!

2023-11-28 06:06 UTC, adionditsak approved these changes

2023-11-28 06:07 UTC, adionditsak commented
@shazkhan2 I have approved this

2024-01-01 15:52 UTC, closed without merging