Databases week2/sevda
HackYourFuture-CPH/class26-homework pull request #353
Opened 2024-07-08 19:13 UTC by Sevda-NZ

Please review HW/week 2 DB

2024-07-13 12:53 UTC, NatsGt requested changes
Good job with your queries, but you need to correct some few. The diagram you created for your example is missing some tables. Additionally, you seem to be having some issue with your repository, you should fix this before merging.

2024-07-13 12:53 UTC, NatsGt commented on 5_databases/week2/part1.sql
> +VALUES (NULL, 'Become a developer', 'Work hard', '2017-10-06 04:03:52', '2017-09-20 19:34:43', '2017-12-22 20:58:03', 2);
You shouldn't add NULL to the id, you can omit this value by `INSERT INTO task (title...) VALUES ('Become a developer', ...)`. Since you stated that **ID** is AUTO_INCREMENT when you created the table, the value will be created automatically.

2024-07-13 12:53 UTC, NatsGt commented on 5_databases/week2/part1.sql
> +WHERE id = 16;
Instead of hardcoding the status_id as 3, you should look for the id of status 'done' using a query.

2024-07-13 12:53 UTC, NatsGt commented on 5_databases/week2/part3.sql
> +SELECT *
Here you should show the tasks of a user, not only the data of users.

2024-07-15 18:31 UTC, Sevda-NZ commented
The reviews are implemented 👍

2024-07-15 18:31 UTC, closed without merging