html-css/Halima
HackYourFuture-CPH/class26-homework pull request #5
Opened 2023-08-18 19:06 UTC by halima770

2023-08-18 19:08 UTC, halima770 commented
homework

2023-08-18 19:31 UTC, mehmetnuricavdar commented on index.html
> +        <li><a href="#">Contact</a></li>
Well written 👏🏼 but links should lead to different parts of the web page.

2023-08-18 19:34 UTC, mehmetnuricavdar commented on index.html
> +              <section id="portfolio">
Why section has 'id' here while the other sections have 'class' ?  I recommend avoiding using 'id' as the best practice is using 'class'

2023-08-18 19:38 UTC, mehmetnuricavdar commented on style.css
> +
I suggest formatting the code with the VS Code extension Prettier for clean code since there are many empty lines.

2023-08-18 19:40 UTC, mehmetnuricavdar commented on style.css
> +    /*line-height: 75px;*/
I guess you were tying the styles but i recommend before submitting the code delete this kind of comment to keep your code clean.

2023-08-18 19:42 UTC, mehmetnuricavdar commented on index.html
> +                </div>
Footer?

2023-08-18 19:43 UTC, mehmetnuricavdar commented on style.css
> +
Same here for deleting unnecessary code before submit.

2023-08-18 19:45 UTC, mehmetnuricavdar commented on index.html
> +                        <i class="fa fa-linkedin" aria-hidden="true"></i>
Can you tell me why you used 'aria-hidden'

2023-08-18 20:01 UTC, mehmetnuricavdar commented on style.css
> +    color:white;
using color codes is better for the future and get used to them from the beginning

2023-08-18 20:09 UTC, mehmetnuricavdar commented on style.css
> +}
You could use only one '@media screen and (max-width: 768px)' and then put styles under it since it is for the same size.

2023-08-18 20:14 UTC, mehmetnuricavdar requested changes
Welcome to HYF! It seems you understand concepts! 
There are some improvements that are needed and it is completely normal, no worries about that. 

First of all, you need to check this HTML/CSS homework folder since it is not in the correct folder as it is inside the general repository.
While I was checking it wasn't deployed to Netlify. You need to do that as well.
You should check styles since about/contact/skills are intertwined.
You added responsiveness but it doesn't work as expected since when most of the content is getting lost you can check it with Chrome inspect.
if you need help you can use support channels on Slack.

2023-08-19 09:37 UTC, halima770 commented
Hello Mehment, thank you for the suggestions you provided. I've implemented the changes you mentioned. However, I'm still experiencing issues with the website's responsiveness. Could you please assist me with addressing this problem?

2023-08-22 19:00 UTC, mehmetnuricavdar commented
Hi Halima, to be able to do your website for different size of screens you and see how ti looks you can use 'inspect' of the browser and set the screen size as desired then you can adjust your styles. Also you can see how i did in the screen video i posted. You may wanna check https://web.dev/learn/design/media-queries/ or ask #html-css-support on Slack.

2023-09-24 15:41 UTC, closed without merging