Javascript-javascript1-week2/eva
HackYourFuture-CPH/class26-homework pull request #87
Opened 2023-09-07 13:24 UTC by yagmureva

done

2023-09-09 09:52 UTC, elilovna requested changes
I see that you learned material, Very good work 😎

2023-09-09 09:52 UTC, elilovna commented on 3_javascript/javascript1/week2/script.js
> +  return firstname + " " + surname;
You could try to use template literals here  😉
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2023-09-09 09:52 UTC, elilovna commented on 3_javascript/javascript1/week2/script.js
> +var fullname1 = getFullname("Benjamin", "Hughes");
it is better to use const or let here

2023-09-09 09:52 UTC, elilovna commented on 3_javascript/javascript1/week2/script.js
> +      return "Lady " + firstname + " " + surname;
you could try to use template literals

2023-09-09 09:52 UTC, elilovna commented on 3_javascript/javascript1/week2/script.js
> +  switch (candyType) {
nice that you used switch

2023-09-17 11:36 UTC, shpomp commented
<img width="687" alt="image" src="https://github.com/HackYourFuture-CPH/class26-homework/assets/64137994/96fa0251-b829-4219-a7e2-b2dc6aa73cde">

2023-09-21 17:25 UTC, closed without merging