Javascript1 week2/halima
HackYourFuture-CPH/class26-homework pull request #94
Opened 2023-09-09 18:38 UTC by halima770

Here is my week 2 JavaScript homework. In the student manager question, I couldn't add  queen in the student class. Could you please help me with that?

2023-09-12 06:41 UTC, danJecu requested changes
Excellent work on your homework, keep it up! 🌟

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +        return "";
It would be beneficial to return a message prompting the user to enter a valid name instead of an empty string.

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +        }
Consider using template literals for string concatenation for more readability.

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +    const eventWeekday = weekdays[futureDate.getDay()];
Great job using the `getDay()` method and indexing into the `weekdays` array. 🥳

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +    return eventWeekday;
The choice of variable names enhances the readability of your code. Well done! 👏🏻

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +    if (class07Students.length >= 6) {
Consider addressing the special case for the Queen first to ensure she can always be added, regardless of class size. 👑

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +        console.log("Cannot add an empty string to the class");
Good job checking for an empty string 👏🏻

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +addStudentToClass("Queen");
Make sure you account for the Queen scenario. It's mentioned in the requirements but hasn't been implemented in the solution.

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +      console.log('Invalid candy type');
Good job handling an invalid candy type with a useful message. 💯

2023-09-12 06:41 UTC, danJecu commented on 3_javascript/javascript1/week2/script.js
> +    return false;
Consider handling edge cases: what if the total cost is exactly equal to the amount to spend? You might want a different message or behavior. 🤔

2023-09-24 15:43 UTC, closed without merging

2023-10-04 06:55 UTC, halima770 commented
thank you for the feedback